config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#index"
  devise_for :users

  resources :posts, only: [:index, :create, :destroy, :show, :new] do
    member do
      post 'like', to: 'likes#create'
      delete 'unlike', to: 'likes#destroy'
    end
    resources :comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index, :show] do
  	resources :friend_requests, only: [:create, :index, :destroy]
  	resources :friends, only: [:create, :index]
  end

  #resources :friend_requests, only: [:destroy]
  resources :friends, only: [:destroy]

  resources :posts, only: [:index, :create, :destroy, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :post

  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates :user,   presence: true
	validates :friend, presence: true, uniqueness: { scope: :user }
  validate :self_req

	private

	def self_req
    if user == friend
		  errors.add(:friend, "cannot send to yourself") 
    end
	end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	after_create :create_inverse
  after_destroy :destroy_inverse

  belongs_to :user
  belongs_to :friend, class_name: 'User'

	validates :user,   presence: true
	validates :friend, presence: true, uniqueness: { scope: :user }
	
  validate :self_req

  private

  def create_inverse
    friend.friendships.create(friend: user)
  end

  def destroy_inverse
    friendship = friend.friendships.find_by(friend: user)
    if friendship 
      friendship.destroy
    end
  end

	private

	def self_req
    if user == friend
		  errors.add(:friend, "cannot be friend of yourself") 
    end
	end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id
  
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {maximum: 100}
  validates :content, presence: true, length: {maximum: 1000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :
  has_many :posts, dependent: :destroy, foreign_key: :author_id 
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def create
    @post = Post.find (params[:post_id])
    @comment = @post.comments.build (comment_params)
    @comment.author = current_user
    if @comment.save
      flash[:notice] = "Comment created."
      redirect_to post_path (@post)
    else
      flash[:alert] = "Failed create comment."
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find (params[:comment_id])
    @post = Post.find (params[:post_id])
    if @comment.destroy
      flash[:notice] = "Comment deleted"
      redirect_to post_path(@post)
    else
      flash[:notice] = "Failed to delete comment"
      render 'posts/show'
    end
  end

  private

  def comment_params 
    params.require(:comment).permit(:content)
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController

	def create
		@friend_request = FriendRequest.create(user_id: params[:user_id], friend_id: current_user.id)
		if @friend_request.save
			flash[:notice] = "Friend request sent"
			redirect_to user_path(params[:user_id])
		else
			flash[:alert] = "Could not send request"
			redirect_to root_path
		end
	end

	def index
		@friend_requests = current_user.friend_requests.all
	end

	def destroy
		@friend_request = FriendRequest.find(params[:id])
		if @friend_request.destroy
			flash[:notice] = "Friend request deleted"
			redirect_to user_path(current_user)
		else
			flash[:alert] = "Could not delete request"
			redirect_to root_path
		end
	end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index
		@friends = current_user.friendships.all.page(params[:page]).per(10)
	end 
  
  def show 
    @friend = Friendship.find_by(user_id: current_user.id, friend_id: params[:friend_id])
  end

	def create
		@friendship = Friendship.new(user_id: current_user.id, friend_id: params[:friend_id])
		if @friendship.save
			flash[:notice] = "Friendship accepted"
			request = FriendRequest.find_by(user_id: current_user.id, friend_id: params[:friend_id])
			request.destroy
			redirect_to user_path(params[:friend_id])
		else
			flash[:notice] = "Can not accept request"
			redirect_to user_path(params[:friend_id])
      
		end
	end

	
	def destroy
		@friendship = Friendship.find_by(friend_id: params[:id], user_id: current_user.id)
		if @friendship.destroy
			flash[:notice] = "Friendship deleted"
			redirect_to users_path
		else
			flash[:notice] = "Unable to destroy friendship"
			redirect_to users_path
		end
	end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!


  def create
    @post = Post.find(params[:id])
    @like = @post.likes.new(author: current_user)

    if @like.save
      flash[:notice] = "Post liked."
    else
      flash[:alert] = "Unable to like post."
    end
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:id])
    @like = @post.likes.find_by(author: current_user)

    if @like.destroy
      flash[:notice] = "Like removed."
    else
      flash[:alert] = "Unable to remove like."
    end
    redirect_to request.referer
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    friends_ids = current_user.friends.pluck(:id)
    @posts = Post.where(author_id: [current_user.id] + friends_ids).page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id]) 
    @user_liked = @post.likes.exists?(author_id: current_user.id)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created"
      redirect_to posts_path
    else
      flash[:alert] = "Unable to create post"
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post deleted"
      redirect_to posts_path
    else
      flash[:alert] = "Failed to destroy post"
      redirect_to post_path(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/friend_requests/_friend_request.html.erb
<div class="request-item">
  <p class="request-username">
    <%= User.find(friend_request.friend_id).username %>
  </p>
  <div class="request-actions">
    <%= button_to "Cancel Request", user_friend_request_path(current_user, friend_request), method: :delete, class: "cancel-button" %>
    <%= button_to "Accept Request", "/users/#{current_user.id}/friends", method: :post, params: { friend_id: friend_request.friend_id }, class: "accept-button" %>
  </div>
</div>

app/views/friend_requests/index.html.erb
<div class="container">
  <h1 class="title">Your Requests</h1>
  <ul class="list">
    <% if @friend_requests.any? %>
      <%= render @friend_requests %>
    <% else %>
      <p class="message">No one wants to be your friend</p>
    <% end %>
  </ul>
</div>

app/views/posts/_form.html.erb
<div class="form-container">
  <%= form_for @post do |f| %>
    <div class="mb-4">
      <%= f.label :title, "Title", class: "form-label" %>
      <%= f.text_field :title, placeholder: "Your title here", class: "form-input" %>
    </div>
    <div class="mb-4">
      <%= f.label :content, "Content", class: "form-label" %>
      <%= f.text_area :content, placeholder: "Your post content goes here", class: "form-textarea" %>
    </div>
    <%= f.submit "Post", class: "form-submit" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <h3 class="post-title"> <%= post.title %></h3>
  
  <br>
  <p class="post-content"><%= post.content %></p>
  
  <p class="post-meta">
    By <%= post.author.username %>
    Posted on <%= post.created_at.strftime("%B %d, %Y %H:%M") %>
    <span class="ml-4">Likes: <%= post.likes.count %></span>
  </p>

  <ul class="comment-list">
    <% post.comments.each do |comment| %>
      <li class="comment-item">
        <p class="comment-content"><%= comment.content %></p>
        <p class="comment-meta">
          By <%= comment.author.username %>
          <span class="ml-4">Posted on <%= comment.created_at.strftime("%B %d, %Y %H:%M") %></span>
        </p>
        <% if current_user.id == comment.author_id %>
          <%= button_to "Delete comment", post_comment_path(post, comment), method: :delete, class: "comment-delete" %>
        <% end %>
      </li>
    <% end %>
  </ul>

  <%#render 'shared/paginator', collection: post.comments.page(params[:page]).per(10) %>
  
  <div class="comment-form">
    <%= form_for([post, post.comments.build]) do |f| %>
      <div class="flex">
        <%= f.text_field :content, placeholder: "Your comment here", class: "input-field" %>
        <%= f.submit "Post", class: "submit-button" %>
      </div>
    <% end %>
  </div>

  <div class="flex space-x-2">
    <% if post.likes.exists?(author: current_user) %>
      <%= form_with url: unlike_post_path(post), method: :delete, local: true, class: "inline" do %>
        <%= submit_tag "Unlike", class: "unlike-button" %>
      <% end %>
    <% else %>
      <%= form_with url: like_post_path(post), method: :post, local: true, class: "inline" do %>
        <%= submit_tag "Like", class: "like-button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="newsfeed-container">
  <h1 class="newsfeed-title">Newsfeed</h1>
  <ul class="post-list">
    <%= render @posts %>
  </ul>

  <%#render 'shared/paginator', collection: @posts %>
  
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/users/_user.html.erb
<li class="user-item">
  <div class="user-info">
    <%= link_to user.username, user, class: "user-link" %> | <%= user.email %>
  </div>
</li>

app/views/users/index.html.erb
<div class="container">
  <h1 class="title">Users</h1>
  <ul class="list">
    <%= render @users %>
  </ul>
  <%#render 'shared/paginator', @users%>
  
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="header-title"><%= @user.username %>'s Profile</div>
  <div class="content">
    <p class="meta"><%= @user.email %></p>
  </div>

  <% if @user.friends.include?(current_user) %>
    <div class="list-item">
      <span class="text-gray-700">You're already friends</span>
      <%= form_with url: friend_path(@user), method: :delete, local: true, class: "inline" do %>
        <%= submit_tag "Unfriend", class: "unlike-button", data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>

    <ul class="post-list">
      <%= render @posts %>
    </ul>
    <%#render 'shared/paginator', collection: @posts %>

  <% elsif FriendRequest.where(friend_id: current_user.id, user_id: @user.id).any? %>
    <div class="list-item">
      <span class="text-gray-700">Friend request pending</span>
    </div>

    <ul class="post-list">
      <%= render @posts %>
    </ul>
    <%#render 'shared/paginator', collection: @posts %>

  <% elsif current_user.email == @user.email %>
    <div class="form-container">
      <% @post = Post.new %>
      <%= render "posts/form" %>
    </div>

    <ul class="post-list">
      <%= render @posts %>
    </ul>
    <%#render 'shared/paginator', collection: @posts %>

  <% else %>
    <div class="list-item">
      <%= form_with url: user_friend_requests_path(@user), method: :post, local: true, class: "inline" do %>
        <%= submit_tag "Send Friend Request", class: "form-submit" %>
      <% end %>
    </div>

    <ul class="post-list">
      <%= render @posts %>
    </ul>
    
  <% end %>
</div>